### PR TITLE
Fix: Private collectors no longer working

### PR DESCRIPTION
**Pull request by ndench**
PR and tests to fix qossmic/deptrac#1435.

---

The [`private: true` collector](https://qossmic.github.io/deptrac/collectors/#extra-collector-configuration) would allow us to do that really easily, but it seems to have stopped working.

We can see in the [PR that added private collectors](https://github.com/qossmic/deptrac/pull/905/files#diff-e9502a67d3bef5407b7fb6b7c8cb17ed6c4c8940502c030d9bfc62e6126b6126) the dependency would be allowed if:
- The dependent layer is _not public_
- The dependent layer __does not equal__ the depender layer

```php
!$isPublic && $dependerLayer !== $dependentLayer
```

However, this logic seems to have been changed when the [violations were improved](https://github.com/qossmic/deptrac/pull/1105/files#diff-efa7f34c2779810259ccd7158c42347c8fa29881977c5b0c3390c13229a34493), now it will allow the dependency if:
- The dependent layer is _not public_
- The dependent lawyer __equals__ the depender layer

```php
$event->dependerLayer === $dependentLayer && !$isPublic
```

### CODE REVIEW

**Review by patrickkusebauch — APPROVED** [review]

**Comment by gennadigennadigennadi** [comment]
@ndench thank you very much for this fix. I'll try to tag a new release in the next few days.

**Comment by ndench** [comment]
Thanks @gennadigennadigennadi. Any chance we can get that release tagged soon?

**Comment by gennadigennadigennadi** [comment]
@ndench maybe coming week I have the time.

**Comment by gennadigennadigennadi** [comment]
@ndench i just open a PR for the next release. Would you be so kind and try it out? 
Does it fix your problem?

**Comment by gennadigennadigennadi** [comment]
https://github.com/qossmic/deptrac/pull/1441

**Comment by ndench** [comment]
@gennadigennadigennadi confirming that the issue is fixed when running with https://github.com/qossmic/deptrac/pull/1441 
Thanks! :smile:

**Pull request merged**
